  version: '3.8'
  services:
    redis:
      image: "redis:6.2-alpine"
      hostname: redis
      volumes:
        - cache:/data
      ports:
        - "6379:6379"
  volumes: 
    cache:
      driver: local